apiVersion: storage.k8s.io/v1
kind: StorageClass
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
metadata:
  name: local-storage
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zfile-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: zfile-pv-claim
    namespace: webservices
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt/zfile
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - vm-8-9-centos
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zfile-pv-claim
  namespace: webservices
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi